name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
    paths:
      - 'backend(FastAPI+Python)/**'

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Estrategia Robusta: Clonar, Copiar y Subir
          git config --global user.email "robe-arango-academy@example.com"
          git config --global user.name "Epic Dreams Studio Academy"
          
          git clone https://epicdreams:$HF_TOKEN@huggingface.co/spaces/epicdreams/epic-dreams-backend hf_space
          
          # Sincronizamos archivos (excluyendo .git)
          cp -rv "backend(FastAPI+Python)"/* hf_space/
          
          cd hf_space
          git add .
          if git diff --staged --quiet; then
            echo "No changes to deploy"
          else
            git commit -m "Deploy from GitHub Actions: $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin main
          fi
